
CREATE TABLE IF NOT EXISTS `pl_post` (
  `post_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `post_type_id` tinyint(3) unsigned NOT NULL,
  `post_feedback_type_id` tinyint(4) NOT NULL,
  `title` varchar(150) DEFAULT NULL,
  `search_term` varchar(150) DEFAULT NULL,
  `content` longtext,
  `data_packet` longtext,
  `location` varchar(100) DEFAULT NULL,
  `latitude` varchar(15) DEFAULT NULL,
  `longitude` varchar(15) DEFAULT NULL,
  `count_like` bigint(20) NOT NULL DEFAULT '0',
  `count_share` bigint(20) NOT NULL DEFAULT '0',
  `count_comment` bigint(20) NOT NULL DEFAULT '0',
  `count_view` bigint(20) NOT NULL DEFAULT '0',
  `is_comment_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `is_like_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `is_share_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `status` enum('inactive','active','baned') NOT NULL DEFAULT 'inactive',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`post_id`),
  KEY `title` (`title`),
  KEY `search_term` (`search_term`),
  KEY `post_type_id` (`post_type_id`),
  KEY `created_at` (`created_at`),
  KEY `location` (`location`),
  KEY `latitude` (`latitude`),
  KEY `longitude` (`longitude`),
  KEY `count_like` (`count_like`),
  KEY `count_comment` (`count_comment`),
  KEY `count_view` (`count_view`),
  KEY `count_share` (`count_share`),
  KEY `post_feedback_type_id` (`post_feedback_type_id`),
  KEY `is_comment_enabled` (`is_comment_enabled`),
  KEY `is_like_enabled` (`is_like_enabled`),
  KEY `is_share_enabled` (`is_share_enabled`),
  FULLTEXT KEY `content` (`content`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;